# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.


development:
email_provider_username: <%= ENV[jdooley26996@gmail.com] %>
email_provider_password: <%= ENV[10000Aweek$] %>
mailchimp_api_key: <%= ENV[7d98c4719ef2596347c4b855154a6096-us11] %>
mailchimp_list_id: <%= ENV[aa63f8c811] %>
domain_name: example.com
owner_email: <%ENV[jdooley26996@gmail.com]

  secret_key_base: 90b06c29787c2094d9cc65bf45fd3016ff841a3130d6b42d6fa698e3623f0bd5eb219b853208f2e5284d2a1325eed8a9f94d426177a0a764216df91ababbd86e

test:
  secret_key_base: a21d6c52b718bae00e15e67041b0c366dfd56f76294faab39e7f03b9bb5326edc799eccb1692821a33f5e5c28fed7b9812dcc6deb8df88eb2350c2b7993a178a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
email_provider_username: <%= ENV[jdooley26996@gmail.com] %>
email_provider_password: <%= ENV[10000Aweek$] %>
mailchimp_api_key: <%= ENV[7d98c4719ef2596347c4b855154a6096-us11] %>
mailchimp_list_id: <%= ENV[aa63f8c811] %>
domain_name: example.com
owner_email: <%ENV[jdooley26996@gmail.com]
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
